### ISSUE TITLE
Failed to load plugin jasmine

### ISSUE THREAD

**Issue by willgm** [tlvince/eslint-plugin-jasmine#44] opened 2016-03-10 21:57 UTC
Getting the following error:

```
ERROR in ./index.js
Module build failed: Error: Failed to load plugin jasmine: Cannot find module 'eslint-plugin-jasmine'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports.load (/Users/williammartins/proj/password-manager-client/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/williammartins/proj/password-manager-client/node_modules/eslint/lib/config/plugins.js:138:21)
    at Object.load (/Users/williammartins/proj/password-manager-client/node_modules/eslint/lib/config/config-file.js:443:21)
    at loadConfig (/Users/williammartins/proj/password-manager-client/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/Users/williammartins/proj/password-manager-client/node_modules/eslint/lib/config.js:129:23)
```

In my `package.json`:

```
    "eslint": "2.3.0",
    "eslint-loader": "1.3.0",
    "eslint-plugin-jasmine": "1.6.0",
    "eslint-plugin-react": "4.2.0",
    "eslint-plugin-sort-class-members": "1.0.0",
    "estraverse-fb": "1.3.1",
    "jasmine": "2.4.1",
    "jasmine-core": "2.4.1",
```

In my `.eslintrc`:

```
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:jasmine/recommended"
  ],
  "parser": "babel-eslint",
  "plugins": [
    "sort-class-members",
    "react",
    "jasmine"
  ],
```

**Comment by tlvince** [comment] 2016-04-04 13:40
Hmm, that set up looks fine to me. Does this still happen with v1.8.0?

**Comment by burabure** [comment] 2016-11-05 19:21
couldn't reproduce, closing. Feel free to re-open with an exmaple failing repo/gist

**Closed by burabure** 2016-11-05 19:21 UTC
